Algoritmo "semnome"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/03/2024
Var
// Seção de Declarações das variáveis
   pes, metros : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   escreva("Informe a medida para ser convertida para metros : ")
   leia(pes)

   metros <- 0.3048 * pes
   

   escreval(" A medida é : ", metros)



Fimalgoritmo