Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/03/2024
Var
// Seção de Declarações das variáveis 
   x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
      para x <- 1 ate 100 passo 1 faça
           se(x mod 2 = 0 ) entao
                escreval(x)
           fimse
      fimpara

Fimalgoritmo