Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/03/2024
Var
// Seção de Declarações das variáveis 
   n, soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   soma <- 0
   n <- 1
   
   enquanto n > 0 faça
       escreva("Digite um numero: ")
       leia(n)
       
       soma <- soma + n
   fimenquanto
   
   escreval("Soma total = ", soma)

Fimalgoritmo