CREATE DATABASE LISTA11;

USE LISTA11;

CREATE TABLE PRICES(
	ID_PRICES				INT						NOT NULL,
	CATEGORIE_PRICE			VARCHAR(100)			NOT NULL,
    VALUE_PRICE				FLOAT				NOT NULL,
    PRIMARY KEY				(ID_PRICES)
);


CREATE TABLE MOVIES(
	ID_MOVIES				INT						NOT NULL,
    NAME_MOVIES				VARCHAR(100)			NOT NULL,
    PRICES_ID				INT						NOT NULL,
    PRIMARY KEY				(ID_MOVIES),
    CONSTRAINT 				FK_PRICES_MOVIES		FOREIGN KEY(PRICES_ID)			REFERENCES PRICES(ID_PRICES)
);

INSERT INTO MOVIES (ID_MOVIES, NAME_MOVIES, PRICES_ID)
VALUES (1, 'BATMAN', 3),
	   (2, 'THE BATTLE OF THE DARK RIVER', 3),
	   (3, 'WHITE DUCK', 5),
	   (4, 'BREAKING BARRIES',4),
       (5, 'THE TWO HOURS',2);
       
INSERT INTO PRICES (ID_PRICES, CATEGORIE_PRICE	, VALUE_PRICE)
VALUES (1, 'RELEASES', 3.50),
	   (2, 'BRONZE SEAL', 2.00),
	   (3, 'SILVER SEAL', 2.50),
	   (4, 'GOLD SEAL',3.00),
       (5, 'PROMOTION',1.50);
       
CREATE VIEW VIEW_MOVIES_PRICES AS
SELECT PR.ID_MOVIES, PR.NAME_MOVIES
FROM MOVIES PR
JOIN PRICES P ON P.ID_PRICES = PR.PRICES_ID
WHERE( P.VALUE_PRICE < 2.00);   

SELECT * FROM VIEW_MOVIES_PRICES;   


