CREATE DATABASE LISTA06;

USE LISTA06;

CREATE TABLE PROVIDERS(
	ID_PROVIDERS				INTEGER(10)								NOT NULL,
	NAME_PROVIDERS	    		VARCHAR(100)							NOT NULL,
    STREET_PROVIDERS			VARCHAR(100) 							NOT NULL,
    CITY_PROVIDERS				VARCHAR(100)							NOT NULL,
    STATE_PROVIDERS				CHAR(10)								NOT NULL,
	PRIMARY KEY(ID_PROVIDERS)
);

INSERT INTO PROVIDERS (ID_PROVIDERS, NAME_PROVIDERS, STREET_PROVIDERS, CITY_PROVIDERS, STATE_PROVIDERS)
VALUES (1, 'HENRIQUE', 'AV. BRASIL', 'RIO DE JANEIRO', 'RJ'),
	   (2, 'MARCELO AUGUSTO', 'RUA IMIGRANTES', 'BELO HORIZONTE', 'MG'),
	   (3, 'CAROLINA SILVA',  'AV. SÃO PAULO',  'SALAVADOR', 'BA'),
	   (4, 'GUILERME STAFF', 'RUA CENTRAL', 'PORTO ALEGRE', ' RS'),
       (5, 'ISABELA MORAES', 'AV. JUIZ GRANDE', 'CURITIBA', 'PR'),
       (6, 'FRANCISCO ACERR', 'AV. PAULISTA', 'SÃO PAULO', 'SP');
       
CREATE VIEW VIEW_PROVIDERS AS
SELECT
	CITY_PROVIDERS
FROM
	PROVIDERS;
    
SELECT * FROM VIEW_PROVIDERS;