// <auto-generated />
using Aula_04.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aula_04.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319123310_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aula_04.Models.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Aula_04.Models.CategoriaProduto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Categoria_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Produto_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria_Id");

                    b.HasIndex("Produto_Id");

                    b.ToTable("CategoriaProdutos");
                });

            modelBuilder.Entity("Aula_04.Models.Fornecedor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("Aula_04.Models.Produto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Fornecedor_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Fornecedor_Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Aula_04.Models.CategoriaProduto", b =>
                {
                    b.HasOne("Aula_04.Models.Categoria", "Categorias")
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("Categoria_Id")
                        .IsRequired();

                    b.HasOne("Aula_04.Models.Produto", "Produtos")
                        .WithMany("CategoriaProdutos")
                        .HasForeignKey("Produto_Id")
                        .IsRequired();

                    b.Navigation("Categorias");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Aula_04.Models.Produto", b =>
                {
                    b.HasOne("Aula_04.Models.Fornecedor", "Fornecedores")
                        .WithMany("Produtos")
                        .HasForeignKey("Fornecedor_Id")
                        .IsRequired();

                    b.Navigation("Fornecedores");
                });

            modelBuilder.Entity("Aula_04.Models.Categoria", b =>
                {
                    b.Navigation("CategoriaProdutos");
                });

            modelBuilder.Entity("Aula_04.Models.Fornecedor", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("Aula_04.Models.Produto", b =>
                {
                    b.Navigation("CategoriaProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
