CREATE DATABASE LISTA02;

USE LISTA02;

CREATE TABLE CUSTOMERS(
	ID_CUSTOMERS						INTEGER					NOT NULL,
    NAME_CUSTOMERS						VARCHAR(100)			NOT NULL,
    STREET_CUSTOMERS					VARCHAR(100)			NOT NULL,
	CITY_CUSTOMERS						VARCHAR(100)			NOT NULL,
    STATE_CUSTOMERS 					CHAR(16)				NOT NULL,
    CREDIT_LIMIT_CUSTOMERS				INTEGER					NOT NULL,
    PRIMARY KEY(ID_CUSTOMERS)
);

#INSERT
INSERT INTO CUSTOMERS (ID_CUSTOMERS, NAME_CUSTOMERS, STREET_CUSTOMERS, CITY_CUSTOMERS, STATE_CUSTOMERS, CREDIT_LIMIT_CUSTOMERS)
VALUES (1, 'PEDRO AUGUSTO DA ROCHA', 'RUA PEDRO CARLOS HOFFMAN', 'PORTO ALEGRE', 'RS', 700.00),
	   (2, 'ANTONIO CARLOS MAMEL',   'AV. PINHEIROS', 'BELO HORIZONTE', 'MG', 3500.50),
	   (3, 'LUIZA AUGUSTA MHOR', 'RUA SALTO GRANDE', 'NITEROI', 'RJ', 4000.00),
	   (4, 'JANE ESTER', 'AV. 7 DE SETEMBRO', 'ERECHIM', 'RS', 800.00),
       (5, 'MARCOS ANTÔNIO DOS SANTOS', 'AV. FARRAPOS', 'PORTO ALEGRE', 'RS', 4250.25);
       
#QUERY SELECT
#OUTPUT SAMPLE
SELECT NAME_CUSTOMERS  FROM CUSTOMERS 
WHERE (CITY_CUSTOMERS = 'PORTO ALEGRE');
#TODAS AS TABELAS
SELECT * FROM CUSTOMERS;