CREATE DATABASE LISTA03;

USE LISTA03;

CREATE TABLE PRODUCTS(
	ID_PRODUCTS 		INT 			NOT NULL,
    NAME_PRODUCTS		VARCHAR(100)	NOT NULL,
    AMOUNT_PRODUCTS		INT				NOT NULL,
    PRICE_PRODUCTS		FLOAT			NOT NULL,
	PRIMARY KEY(ID_PRODUCTS)
);

#INSERT
INSERT INTO PRODUCTS (ID_PRODUCTS, NAME_PRODUCTS, AMOUNT_PRODUCTS, PRICE_PRODUCTS)
VALUES (1, 'TWO-DOOR WARDROBLE', 100, 80),
	   (2, 'DINING TABLE',  1000, 560),
	   (3, 'TOWEL HOLDER', 10000, 5.50),
	   (4, 'COMPUTER DESK', 350, 100),
       (5, 'CHAIR', 3000, 210.64),
       (6, 'SINGLE BED', 750, 99);
       
       
#QUERY SELECT
SELECT ID_PRODUCTS, NAME_PRODUCTS FROM PRODUCTS WHERE (AMOUNT_PRODUCTS >= 1000);
	