CREATE DATABASE LISTA13;

USE LISTA13;

CREATE TABLE CUSTOMERS(
	ID_CUSTOMERS						INTEGER					NOT NULL,
    NAME_CUSTOMERS						VARCHAR(100)			NOT NULL,
    STREET_CUSTOMERS					VARCHAR(100)			NOT NULL,
	CITY_CUSTOMERS						VARCHAR(100)			NOT NULL,
    PRIMARY KEY(ID_CUSTOMERS)
);


#INSERT
INSERT INTO CUSTOMERS (ID_CUSTOMERS, NAME_CUSTOMERS, STREET_CUSTOMERS, CITY_CUSTOMERS)
VALUES (1, 'GIOVANNA G. OLIVEIRA', 'RUA MATO GROSSO','CANOAS'),
	   (2, 'KAUÃ AZEVEDO RIBEIRO', 'TRAVESSA IBIÁ', 'UBERLÂNDIA'),
	   (3, 'REBECA BARBOSA SANTOS','RUA OBSERVATÓRIO METEOROLÓGICO','SALVADOR'),
	   (4, 'SARAH CARVALHO CORREIA','RUA ANTÔNIO CARLOS DA SILVA','APUCARANA'),
       (5, 'JOÃO ALMEIDA LIMA','RUA RIO TAIUVA','PONTA GROSSA'),
       (6, 'DIOGO MELO DIAS','RUA DUZENTOS E CINQÜENTA','VÁRZEA GRANDE');

SELECT * FROM CUSTOMERS;
       
CREATE VIEW VIEW_COSTUMERS_49 AS       
SELECT CITY_CUSTOMERS FROM CUSTOMERS;

SELECT * FROM VIEW_COSTUMERS_49;