CREATE DATABASE LISTA12;

USE LISTA12;

CREATE TABLE CUSTOMERS(
	ID_CUSTOMERS						INTEGER					NOT NULL,
    NAME_CUSTOMERS						VARCHAR(100)			NOT NULL,
    STREET_CUSTOMERS					VARCHAR(100)			NOT NULL,
	CITY_CUSTOMERS						VARCHAR(100)			NOT NULL,
    PRIMARY KEY(ID_CUSTOMERS)
);


CREATE TABLE RENTALS(
	ID_RENTALS							INTEGER					NOT NULL,
    DATE_RENTALS						DATE                    NOT NULL,
    PRIMARY KEY(ID_RENTALS)												,
	CUSTOMERS_ID						INTEGER					NOT NULL,
    CONSTRAINT 							FK_CUSTOMERS_RENTALS	FOREIGN KEY(CUSTOMERS_ID)		REFERENCES CUSTOMERS(ID_CUSTOMERS)
);

#INSERT
INSERT INTO CUSTOMERS (ID_CUSTOMERS, NAME_CUSTOMERS, STREET_CUSTOMERS, CITY_CUSTOMERS)
VALUES (1, 'GIOVANNA G. OLIVEIRA', 'RUA MATO GROSSO','CANOAS'),
	   (2, 'KAUÃ AZEVEDO RIBEIRO', 'TRAVESSA IBIÁ', 'UBERLÂNDIA'),
	   (3, 'REBECA BARBOSA SANTOS','RUA OBSERVATÓRIO METEOROLÓGICO','SALVADOR'),
	   (4, 'SARAH CARVALHO CORREIA','RUA ANTÔNIO CARLOS DA SILVA','APUCARANA'),
       (5, 'JOÃO ALMEIDA LIMA','RUA RIO TAIUVA','PONTA GROSSA'),
       (6, 'DIOGO MELO DIAS','RUA DUZENTOS E CINQÜENTA','VÁRZEA GRANDE');
       
INSERT INTO RENTALS (ID_RENTALS,   DATE_RENTALS , CUSTOMERS_ID)
VALUES 	(1,'2016-09-10',3),
		(2,'2016-02-09',1),
		(3,'2016-02-08',4),
		(4,'2016-02-09',2),
		(5,'2016-02-03',6),
        (6,'2016-04-04',4);
        
 SELECT * FROM CUSTOMERS;
 
CREATE VIEW VIEW_COSTUMERS_RENTALS AS
SELECT PR.NAME_CUSTOMERS, P.DATE_RENTALS
FROM CUSTOMERS PR
LEFT JOIN RENTALS P ON PR.ID_CUSTOMERS = P.CUSTOMERS_ID
WHERE( DATE_RENTALS = '2016-09-10');   

SELECT * FROM VIEW_COSTUMERS_RENTALS;   
	  
       
       
       
