CREATE DATABASE LISTA09;

USE LISTA09;

CREATE TABLE PRODUCTS(
	ID_PRODUCTS 				INTEGER(10) 						NOT NULL,
    NAME_PRODUCTS				VARCHAR(100)						NOT NULL,
    AMOUNT_PRODUCTS				INT(10)								NOT NULL,
    PRICE_PRODUCTS				FLOAT								NOT NULL
);

#INSERT
INSERT INTO PRODUCTS (ID_PRODUCTS, NAME_PRODUCTS, AMOUNT_PRODUCTS, PRICE_PRODUCTS)
VALUES 	(1, 'TWO-DOOR WARDROBLE', 100, 800),
		(2, 'DINING TABLE',  1000, 560),
		(3, 'TOWEL HOLDER', 10000, 25.50),
		(4, 'COMPUTER DESK', 350, 320.50),
		(5, 'CHAIR', 3000, 210.64),
		(6, 'SINGLE BED', 750, 460);       
        
        
CREATE VIEW VIEW_PRODUCTS AS
SELECT
	AVG(PRICE_PRODUCTS)
FROM
	PRODUCTS;
    
    
SELECT * FROM VIEW_PRODUCTS;