CREATE DATABASE LISTA04;

USE LISTA04;

CREATE TABLE PRODUCTS(
	ID_PRODUCTS 				INTEGER(10) 						NOT NULL,
    NAME_PRODUCTS				VARCHAR(100)						NOT NULL,
    AMOUNT_PRODUCTS				INT(10)								NOT NULL,
    PRICE_PRODUCTS				FLOAT								NOT NULL,
	PRIMARY KEY(ID_PRODUCTS),
    PROVIDERS_ID 				INT(10)								NOT NULL,
    CATEGORIES_ID				INT(10)								NOT NULL,
    CONSTRAINT					FK_PROVIDERS_PRODUCTS     			FOREIGN KEY(PROVIDERS_ID)			REFERENCES PROVIDERS(ID_PROVIDERS),
    CONSTRAINT 					FK_CATEGORIES_PRODUCTS				FOREIGN KEY(CATEGORIES_ID)			REFERENCES CATEGORIES(ID_CATEGORIES)
);

CREATE TABLE CATEGORIES(
	ID_CATEGORIES				INTEGER(10)								NOT NULL,
	NAME_CATEGORIES	    		VARCHAR(100)							NOT NULL,
	PRIMARY KEY(ID_CATEGORIES)
);

#INSERT
#INSERT
INSERT INTO PRODUCTS (ID_PRODUCTS, NAME_PRODUCTS, AMOUNT_PRODUCTS, PRICE_PRODUCTS, CATEGORIES_ID)
VALUES 	(1, 'TWO-DOOR WARDROBLE', 100, 800, 1),
		(2, 'DINING TABLE',  1000, 560, 3 ),
		(3, 'TOWEL HOLDER', 10000, 25.50, 4 ),
		(4, 'COMPUTER DESK', 350, 320.50, 2),
		(5, 'CHAIR', 3000, 210.64, 4),
		(6, 'SINGLE BED', 750, 460, 1);       
       

INSERT INTO CATEGORIES (ID_CATEGORIES, NAME_CATEGORIES)
VALUES (1, 'OLD STOCK'),
	   (2, 'NEW STOCK'),
	   (3, 'MODERN'),
	   (4, 'COMMERCIAL'),
       (5, 'RECYCLABLE'),
       (6, 'EXECUTIVE'),
       (7, 'SUPERIOR'),
       (8, 'WOOD'),
       (9, 'SUPER LUXURY'),
       (10, 'VINTAGE');

CREATE VIEW VIEW_PROVIDERS AS
SELECT P.ID_PRODUCTS, P.AMOUNT_PRODUCTS, PR.NAME_CATEGORIES
FROM PRODUCTS P
JOIN CATEGORIES PR ON PR.ID_CATEGORIES = P.CATEGORIES_ID;