CREATE DATABASE LISTA10;

USE LISTA10;

CREATE TABLE GENRES(
	ID_GENRES 			INT 					NOT NULL,
    DESCRIPT_GENRES		VARCHAR(100)			NOT NULL,
    PRIMARY KEY(ID_GENRES)
);

CREATE TABLE MOVIES(
	ID_MOVIES			INT						NOT NULL,
    NAME_MOVIES			VARCHAR(100)			NOT NULL,
    GENRES_ID			INT						NOT NULL,
    PRIMARY KEY			(ID_MOVIES),
    CONSTRAINT 			FK_GENRES_MOVIES		FOREIGN KEY(GENRES_ID)			REFERENCES GENRES(ID_GENRES)
);

INSERT INTO MOVIES (ID_MOVIES, NAME_MOVIES, GENRES_ID)
VALUES (1, 'BATMAN', 3),
	   (2, 'THE BATTLE OF THE DARK RIVER', 3),
	   (3, 'WHITE DUCK', 1),
	   (4, 'BREAKING BARRIES',4),
       (5, 'THE TWO HOURS',2);
       
INSERT INTO GENRES (ID_GENRES, DESCRIPT_GENRES)
VALUES (1, 'ANIMATION'),
	   (2, 'HORROR'),
	   (3, 'ACTION'),
	   (4, 'DRAMA'),
       (5, 'COMEDY');

CREATE VIEW VIEW_MOVIES_GENRES AS
SELECT P.ID_GENRES, PR.NAME_MOVIES
FROM GENRES P
JOIN MOVIES PR ON P.ID_GENRES = PR.GENRES_ID
WHERE( P.ID_GENRES = 3);

SELECT * FROM VIEW_MOVIES_GENRES;

