Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/02/2024
Var
// Seção de Declarações das variáveis 
   idade: inteiro
   nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva("Informe seu nome:")
   leia(nome)
   escreva("Informe sua Idade:")
   leia(idade)
   
   escreva("Seu nome é ",nome, " e possui ",idade, " anos de idade")

Fimalgoritmo