Algoritmo "semnome"
// 
//  
// 11. Faça um programa que receba um número e mostre o resto da divisão por 6.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/03/2024
Var
// Seção de Declarações das variáveis 
    resto, num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Entre com um valor : ")
   leia(num)

   resto <- num MOD 2
   
   escreval("O resto da divisão é", " : ", resto)
Fimalgoritmo