Algoritmo "semnome"
// 
//  
// 06. Efetuar a leitura de um número inteiro e apresentar o resultado do quadrado desse número.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/03/2024
Var
// Seção de Declarações das variáveis 
     num1, resul: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

     escreva("Informe o numero: ")
     leia(num1)
     
     resul <- (num1 ^ 2 )
      
     escreval("o valor de um numero ao quadrado é"," : ", resul)

Fimalgoritmo