Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2024
Var
// Seção de Declarações das variáveis 
      i, valor :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   para i de 1 até 5 passo 1 faça
        leia(valor)
        escreval(valor * valor)
   fimpara

Fimalgoritmo