Algoritmo "Somando dois numeros"
//
//
// 01. Faça um algoritmo que receba 2 números inteiros e apresente a soma desses números.

Var
// variaveis
   soma, num1, num2: inteiro

Inicio
// Se??o de Comandos, procedimento, fun??es, operadores, etc...
     escreva("Informe o primeiro numero:")
     leia(num1)
     escreva("Informe o segundo numero:")
     leia(num2)

     soma <- num1 + num2
     escreva("o resultado é", soma)
Fimalgoritmo