Algoritmo "semnome"
//  
//  
// 
//  
// 10. Faça um programa que calcule a área da circunferência.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/03/2024
Var
// Seção de Declarações das variáveis 
   area, raio: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   PI

   escreva("Entre com valor do raio : ")
   leia(raio)
   
   area <- PI * (raio ^ 2)
   
   escreval("Area é", " : ", area )

Fimalgoritmo