Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/03/2024
Var
// Seção de Declarações das variáveis 
   i, num1: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Entre com um numero positivo:")
   leia(num1)
 
   para i de 0 ate 10 faca
          escreval(num1 , " * ", i, " = " , num1 * i)
   fimpara

Fimalgoritmo